name: ompay_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  http: ^1.1.0
  get_it: ^9.0.5
  dio: ^5.4.0
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
